before:
  hooks:
    - go mod tidy

builds:
    -
        binary: sigurlfind3r
        main: cmd/sigurlfind3r/main.go
        goos:
            - linux
            - windows
            - darwin
        goarch:
            - amd64
            - 386
            - arm
            - arm64

archives:
    -
        id: tgz
        format: tar.gz
        replacements:
            darwin: macOS
        format_overrides:
            -
                goos: windows
                format: zip
