before:
    hooks:
        - go mod tidy

builds:
    -
        id: hqurlfind3r
        main: cmd/hqurlfind3r/main.go
        env:
            - CGO_ENABLED=0
        binary: hqurlfind3r
        goos:
            - linux
            - darwin
            - windows
        goarch:
            - amd64
            - 386
            - arm
            - arm64

archives:
    -
        id: tgz
        format: tar.gz
        replacements:
            darwin: macOS
        format_overrides:
            -
                goos: windows
                format: zip
