name: build 🔨

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build
        strategy:
            matrix:
                go-version: [1.19.x]
                os: [ubuntu-latest, windows-latest, macOS-12]
        runs-on: ${{ matrix.os }}
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: ${{ matrix.go-version }}
            -
                name: Checkout the code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            - 
                name: Go modules hygine
                run: |
                    go clean -modcache
                    go mod tidy
                working-directory: v2/
            -
                name: Build
                run: go build -v .
                working-directory: v2/cmd/hqurlfind3r