name: release 🎉

on:
    create:
        tags:
            - v*.*.*
    workflow_dispatch:

jobs:
    release:
        name: release
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version:  '>=1.20'
            -
                name: Check out code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0
            -
                name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v4
                with:
                    args: "release --rm-dist"
                    version: latest
                    workdir: v2/
                env:
                    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"